public with sharing class AddAttachmentExt 
{
	/*private ApexPages.StandardController stdCtrl;
	public Attachment att {get; set;}
	
	public AddAttachmentExt(ApexPages.StandardController inStd)
	{
		stdCtrl=inStd;
		att=new Attachment();
	}
	
	public PageReference AddAttachment()
	{
		att.ParentId=stdCtrl.getId();
		insert att;
		
		PageReference pr=new PageReference(ApexPages.currentPage().getUrl());
		pr.setRedirect(true);
		
		return pr;
	}*/
}