public with sharing class BillboardContractListViewSwitchExt {
/*
     public boolean isLtng{get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          } set;
            }  
   
   
    public string BBCid{get;set;}
    public Billboard_Contract__c BBC{get;set;}
  
    public BillboardContractListViewSwitchExt (ApexPages.StandardController controller) {
          BBCid= controller.getRecord().id;
        
        BBC=[select id,name,Billboard__c from Billboard_Contract__c where id=:BBCid];
    }
    
    Public PageReference pagedir()
    {
         String BBid;
         BBid = BBC.Billboard__c;
        PageReference p;
        if(isLtng)
        {
              p =  new Pagereference('/apex/BillboardDetailPageLightning?id='+BBid);            
        }
        else
        {
              p =  new Pagereference('/apex/BillboardDetailPage?id='+BBid);
        } 
          p.setRedirect(true);  
          return p;
    }
*/
}