public with sharing class BillboardDetailPageExtension {

   // Global variables
   /* public List<Billboard__c> BB{get;set;} 
    String theID;
    // End of Global variables
    
    // Start Constructor
    public BillboardDetailPageExtension(ApexPages.StandardController controller) 
    {
         theID = ApexPages.CurrentPage().getParameters().get('id');
         BB=[select id,Name from Billboard__c where id =: theID ];
         
    }*/
    // End of Constructor
}