public with sharing class CampaignTemplateListViewSwitchExt {
/*
Public String CampId {set;get;}
public string CTkeyPrefix;

    public CampaignTemplateListViewSwitchExt(ApexPages.StandardController controller) {
    CampId =controller.getRecord().id;
    CTkeyPrefix=Campaign_Template__c.SobjectType.getDescribe().getKeyprefix();    
    
    }

 public pageReference CTListview(){
 pageReference  p;
 string Theme=Userinfo.getUItheme();
 
 if(Theme=='Theme4d')
  p=new pageReference('/'+CTkeyPrefix+'/o');
  else
   p=new pageReference('/apex/AdminListView?intFocus=15');
   p.setredirect(true);
    return p;
 }*/
    
}