public with sharing class ClientInvoiceDetailPageExtension {

    // Global variables
    /*public List<Client_Invoice__c> ci{get;set;} 
    String theID;
    // End of Global variables
    
    // Start Constructor
    public ClientInvoiceDetailPageExtension(ApexPages.StandardController controller) 
    {
         theID = ApexPages.CurrentPage().getParameters().get('id');
         ci=[select id,Name,Invoice_Status__c from Client_Invoice__c where id =: theID ];
         
    }*/
    // End of Constructor
}