public with sharing class DevItemsTabExt {
/*
    public DevItemsTabExt(ApexPages.StandardSetController controller) {
 		Devprefix=Development_Item__c.SobjectType.getDescribe().getKeyPrefix();
    }


    public boolean isLtng{ set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                        }
            }  

   public string Devprefix {set;get;}

   // public DevItemsTabExt (ApexPages.StandardController controller) {

    // Devprefix=Development_Item__c.SobjectType.getDescribe().getKeyPrefix();
    // ApexPages.addMessage(New Apexpages.Message(Apexpages.severity.info,''+glcodeprefix));
  //  }


    public pageReference Devlistview()
    {
  
       PageReference p ;
       p= new Pagereference('/'+Devprefix+'/o');
       p.setRedirect(true);
       return p;
  
    }

*/
}