public with sharing class DevItemTabOverrideExt {

  /*  public DevItemTabOverrideExt(ApexPages.StandardSetController controller) {

    }
    
     public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d' || theme=='Theme4t')?true:false;
                                          }
    }
    
*/
}