public with sharing class displayCampaginTemplateAdminExt {
/*

    public List<Campaign_Template__c> lstCTempls {get;set;}
    public String strCamTempId {get;set;}

    public displayCampaginTemplateAdminExt(ApexPages.StandardController controller) {
     lstCTempls=new List<Campaign_Template__c>();
     lstCTempls=[select id,Name from Campaign_Template__c Order BY Name LIMIT 10000];
     
    }


  public pagereference deleteCampTemp()
    {
        Pagereference pg = new Pagereference('/apex/DeleteCampaignTemp?id='+strCamTempId );
        pg.setRedirect(true);
        return pg;
    }
    // End of method deleteMediaType
    
    // This method is called on to handle Edit link on list of Media Type
    public pagereference editCampTemp()
    { 
        Pagereference pg = new Pagereference('/apex/editcampaignTemplate?id='+strCamTempId );
        pg.setRedirect(true);
        return pg;
    }
    // End of method editMediaType
    
    // This method is called on to handle Create New Media Type button
    public pagereference createCampTemp()
    {
        Pagereference pg = new Pagereference('/apex/NewcampaignTemplate');
        pg.setRedirect(true);
        return pg;
    }*/

}