public with sharing class DisplayStaff
{
/*
    public DisplayStaff(ApexPages.StandardController controller) 
    {

    }

    public List <Staff__c> lstStaff{get;set;}

    public DisplayStaff() 
    {
    lstStaff=[SELECT First_Name__c,Last_Name__c,Email__c,Username__c from Staff__c LIMIT 10000];
    }


    
  static testMethod void DisplayStaff()
    {
      
         DisplayStaff ext=new DisplayStaff();
          Staff__c Staff = new Staff__c();
          ApexPages.StandardController con=new ApexPages.StandardController(Staff);
          DisplayStaff ext1=new DisplayStaff(con);
          System.assertEquals(null,ext1.lstStaff);
       
    } 
   
*/
}