public with sharing class DisplayBBInvoiceUnderVendor {
/*
// Start Global variables
        transient public List<Billboard_Invoice__c> invoice{get;set;}
        Public String theID;
        public boolean displayinvoice{get;set;}
        public boolean noinvoice{get;set;}
    // End of Global variables
    
    // Start Constructor
     public DisplayBBInvoiceUnderVendor ()
     {
      
         theID = ApexPages.CurrentPage().getParameters().get('id');
         invoice = [Select id,Name,Billboard_Vendor__c,Billboard__c,Billboard__r.Name,BB_Invoice_Due_Date__c,BB_Invoice_Amount__c,Location__c,Billboard_Vendor__r.Name from Billboard_Invoice__c where Billboard_Vendor__c=: theID Order By Name ];
         If(invoice.size()>0)
         {
             displayinvoice=true;
             noinvoice=false;
         }else{
                 noinvoice=true;
                 displayinvoice=false;
               }
     }
     // End constructor


*/

}