//@isTest
public class DisplayJobsUnderCampaign{
   /* static testMethod void DisplayJobsUnderCampaign()
    {
           Campaign__c Camp = new Campaign__c();
           
           // Instantiate the extention instance with the Custom Controller
           DisplayJobsUnderCampaignController ext=new DisplayJobsUnderCampaignController();
           
           DisplayJobsUnderCampaignController ext1=new DisplayJobsUnderCampaignController();
           ext.strStatus = 'All Jobs';
           ext.populateJobList();
           ext.strStatus = 'Active';
           ext.populateJobList();
           
          ext.strStatus= 'Active';
          String strStatus1 = ext.strStatus;
         // ext.strStatus(SpecTempName);
          List<SelectOption> options5 = ext.getStatusList();
           
           System.assertEquals(Camp.id,ext.theID);
    } */
}