public with sharing class EditJobSpecUnderJobSwitchpageExt 
{

   /* public EditJobSpecUnderJobSwitchpageExt(ApexPages.StandardController controller) 
    {

    }

     public boolean isMobile{
                         
                         private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4t')?true:false;
                                          }
                         }
                         
     public boolean isLight{
                         
                         private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          }
                         }     */                
    
}