public class FilesController {			
  /*  @AuraEnabled	  
    public static List<ContentDocumentLink> fetchFiles(String linkedRecId){	       
        List<ContentDocumentLink> cdlList = [SELECT ContentDocumentId,ContentDocument.title,systemmodstamp FROM ContentDocumentLink WHERE LinkedEntityId =: linkedRecId and ContentDocument.title like '%final%'  order by systemmodstamp desc LIMIT 1];	    
        return cdlList;	 
    }*/	
}