public with sharing class GDListViewSwitchExt{
    
 /*   public boolean isLtng{get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                          } set;
            }  
   
   
    public string GDId{get;set;}
    public Graphics_Deliverables__c GD{get;set;}
    
    public GDListViewSwitchExt(ApexPages.StandardController controller) 
    {
        GDId= controller.getRecord().id;
        
        GD=[select id,name,Job__c from Graphics_Deliverables__c where id=:GDId];
        
    }
    
    Public PageReference pagedir()
    {
         String jobid;
         jobid =  GD.Job__c;
         if(isLtng)
        {
             PageReference p =  new Pagereference('/apex/JobdetailpageLightening07?id='+jobId+'&section=GD');
             p.setRedirect(true);
             return p; 
        }
        else
        {
                PageReference p =  new Pagereference('/apex/jobListView?id='+jobId+'&intFocus=11');
                p.setRedirect(true);
                return p;
        } 
    }*/
    

}