public with sharing class InvTempListViewSwitchExt 
{

/*         public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                        }
            }  

        public string INVprefix {set;get;}
    
        public InvTempListViewSwitchExt(ApexPages.StandardController controller) {
    
         INVprefix =Invoice_Allocation_Template__c.SobjectType.getDescribe().getKeyPrefix();
        // ApexPages.addMessage(New Apexpages.Message(Apexpages.severity.info,''+glcodeprefix));
        }
    
    
    public pageReference pagedir(){
      
      PageReference p ;
         if(isLtng)
         {
                p= new Pagereference('/'+INVprefix+'/o');
         
         }
         else
         {
               p = new Pagereference('/apex/AdminListView?intFocus=12');
         
         }
             p.setRedirect(true);
              return p;
      
    }*/



}