public with sharing class JobRequestComponentController
{
    /*public JobRequestComponentController()
    {}
    
    public pagereference navigateToPromoHighlightsJobRequest()
    {
        Pagereference pg = new Pagereference('/apex/JobRequestPromoHighlightsUserTest');
        pg.setRedirect(true);
        return pg;
    }
    
    public pagereference navigateToPromoHighlightsReport()
    {
        Pagereference pg = new Pagereference('/apex/PromoHighlightsReport');
        pg.setRedirect(true);
        return pg;
    }*/
}