public with sharing class JobSuiteHelpPageController 
{
    /*public Document objDoc;
    public String imageBody{get;set;}
    public String imageURL{get;set;}
    
    public JobSuiteHelpPageController()
    {
        imageURL = '/servlet/servlet.FileDownload?file='; 
        objDoc = [Select Id, Name, Body from Document where Name =: 'JobSuite_OrganizationLogo' LIMIT 1];
        String imageId =  objDoc.Id;
 //       imageId = imageId.subString(0,15);
        imageBody = imageURL+imageId;
        System.debug('Document URL is '+imageBody);
    }*/
}