public with sharing class JobslistviewSwitchExt
{
/*
    public boolean isLtng{private set; get{
                                                String theme = UserInfo.getUITheme();
                                                return (theme=='Theme4d')?true:false;
                                            }
                }  
    
    public string Jobprefix{set;get;}

    public JobslistviewSwitchExt(ApexPages.StandardController controller) {

     Jobprefix=job__c.SobjectType.getDescribe().getKeyPrefix();
    // ApexPages.addMessage(New Apexpages.Message(Apexpages.severity.info,''+glcodeprefix));
    }


public pageReference Clientview(){
   PageReference p;
   p =  new Pagereference('/'+Jobprefix+'/o');
   p.setRedirect(true);
   return p;
  
}*/

}