public with sharing class JobTeamAddEditStaffSwitchExt {

   /* public JobTeamAddEditStaffSwitchExt(ApexPages.StandardController controller) {

    }
    
     public boolean isMobile{
                         
                          set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4t')?true:false;
                                          }
                         }
*/
}