public with sharing class MaterialLineDetailPageExtension {

   // Global variables
   /* public List<Material_Item__c> ML{get;set;} 
    String theID;
    // End of Global variables
    
    // Start Constructor
    public MaterialLineDetailPageExtension (ApexPages.StandardController controller) 
    {
         theID = ApexPages.CurrentPage().getParameters().get('id');
         ML=[select id,Name from Material_Item__c where id =: theID ];
         
    }*/
}