public with sharing class MITabExt{

   /* public boolean isLtng{set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                        }
            }  

    public string MIprefix{set;get;}
   
    public MITabExt(ApexPages.StandardSetController controller) 
    {
        MIprefix=Material_Item__c.SobjectType.getDescribe().getKeyPrefix();
    }
    
    public pageReference MIlistview()
    {
  
       PageReference p ;
       p= new Pagereference('/'+MIprefix+'/o');
       p.setRedirect(true);
       return p;
  
    }*/

}