public with sharing class mytestclass {
/*
    public PageReference cancel() {
        return null;
    }


    public PageReference save() {
        return null;
    }


    public PageReference createNewSession() {
        return null;
    }

    public Id jobId{get;set;}  
    public List<Session__c> lstSessions{get;set;}
    
    public mytestclass() {    
        jobId=ApexPages.CurrentPage().getParameters().get('id');
        lstSessions=[Select Id,Job__c,Session_Status__c,Name,GL_Department__c,GL_Code__c,Session_Type__c,Start_Time__c,End_Time__c,Producer__c,Quantity__c,Technician__c,Unit_Cost__c,Vendor__c from Session__c where Job__c=:jobId ORDER BY Name];
    }*/

}