public with sharing class NewJobSpecUnderJobSwitchpageExt
{
    /*public NewJobSpecUnderJobSwitchpageExt(ApexPages.StandardController controller) 
    {
         
    }
    
     public boolean isMobile{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4t')?true:false;
                                          }
    }
    
*/
}