public with sharing class PEListViewSwitchExt 
{
    /*public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                        }
            }  

    public string PETprefix {set;get;}
    
        public PEListViewSwitchExt(ApexPages.StandardController controller) {
    
         PETprefix =Production_Estimate_Template__c.SobjectType.getDescribe().getKeyPrefix();
        // ApexPages.addMessage(New Apexpages.Message(Apexpages.severity.info,''+glcodeprefix));
        }
    
    
    public pageReference pagedir(){
      
      PageReference p ;
         if(isLtng)
         {
                p= new Pagereference('/'+PETprefix +'/o');
         
         }
         else
         {
               p = new Pagereference('/apex/AdminListView?intFocus=13');
         
         }
             p.setRedirect(true);
              return p;
      
    }*/


}