// This class is used to display Role Detail
public with sharing class RoleDetailExtension 
{
 /*   // Global variables
    private final UserRole role;
    // End Global variables
    
    // Start Constructor
    public RoleDetailExtension(ApexPages.StandardController controller)
    {
         this.role= (UserRole)controller.getrecord();
    }
    // End of Constructor
    
   // Test Method 
  static testMethod void Test_RoleDetailExtension()
    {
      UserRole u=new UserRole(Name='Design Manager');
          insert u;
      System.assertEquals('Design Manager',u.Name);
      
      ApexPages.StandardController con=new ApexPages.StandardController(u);
      RoleDetailExtension ext=new RoleDetailExtension(con);
    } 
 // End of test Method*/
}
// End of Class