public with sharing class SessionController {
  
  /*  public List<Session__c> lstSessions {get;set;}
    
    public SessionController()
    {
        lstSessions = [select Id, Session_Status__c, GL_Department__c, Quantity__c, Unit_Cost__c from Session__c];  
    }
    
    public PageReference createNewSession()
    {
        return null;
    }
    public PageReference save()
    {
        return null;
    }
    public PageReference cancel()
    {
        return null;
    */
}