public with sharing class ShipmentDetailPageExtension{

   // Global variables
  /*  public List<Shipment__c> SP{get;set;} 
    String theID;
    // End of Global variables
    
    // Start Constructor
    public ShipmentDetailPageExtension(ApexPages.StandardController controller) 
    {
         theID = ApexPages.CurrentPage().getParameters().get('id');
         SP=[select id,Name from Shipment__c where id =: theID ];
         
    }/*/
    // End of Constructor
}