public with sharing class SpecTemplateDetailSwitchExt {
/*
  public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                        }
            }  
    public string SpecItemId{get;set;}
    public Spec_Item__c  speItem{get;set;}


    public SpecTemplateDetailSwitchExt(ApexPages.StandardController controller) {
    
        SpecItemId=controller.getRecord().id;
        
        speItem=[select id,name,Specification_Template__c from Spec_Item__c where id=:SpecItemId];

    }
    
   
   

public pageReference spedatailview(){
  
  String specTempId=speItem.Specification_Template__c;
    PageReference p;
     if(isLtng)
        p =  new Pagereference('/apex/SpecificationTemplateTabOverrideLti?id='+specTempId);
     else
        p =  new Pagereference('/apex/SpecificationTemplateTabOverride?id='+specTempId);
        p.setRedirect(true);
       return p;
}

 */   

}