public with sharing class TagsTempListviewSwitchExt{
/*
 public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                        }
            }  
 public string TagsTempprefix {set;get;}

    public TagsTempListviewSwitchExt(ApexPages.StandardController controller) {
     TagsTempprefix =Tag_Template__c.SobjectType.getDescribe().getKeyPrefix();
    }


public pageReference Tagslistview(){
  
  PageReference p;
     if(isLtng)
     {
         p =new Pagereference('/'+TagsTempprefix+'/o');
     }
     else
     {
        p =new Pagereference('/apex/AdminListView?intFocus=11');
     }
       p.setRedirect(true);
       return p;
     
  
}*/

}