public with sharing class TagTempLIviewExt{
/*
public boolean isLtng{private set; get{
                                            String theme = UserInfo.getUITheme();
                                            return (theme=='Theme4d')?true:false;
                                        }
            }  
  private final Tag_Template_Item__c objTagLI;
  private Tag_Template_Item__c objTagLIQ;
  public String TagTempID{get;set;}

    public TagTempLIviewExt(ApexPages.StandardController controller) 
    {
          this.objTagLI=(Tag_Template_Item__c)controller.getrecord();
          objTagLIQ=[select id,TagTemplate__c,name from Tag_Template_Item__c where  id =:objTagLI.id];
          TagTempID=objTagLIQ.TagTemplate__c;
          
    
    }


public pageReference Taglistview(){
  
  PageReference p ;
     if(isLtng)
     {
           p = new Pagereference('/apex/TagTemplatedetailpage?id='+TagTempID);
     
     }
     else
     {
           p = new Pagereference('/apex/TagTemplatedetailpage?id='+TagTempID);
     
     }
         p.setRedirect(true);
         return p;
  
}
*/
}