@isTest
public class TestCreateNewJobNewSwitchPageExt {
	/* static TestMethod void TestCreateNewJobNewSwitchPageExt  (){
        Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        CreateNewJobNewSwitchPageExt controller = new CreateNewJobNewSwitchPageExt (new ApexPages.StandardController(testJob1));
        boolean x = controller.isLtng;
    }*/
}