@isTest
public class TestProductionSpecItemsController {
 
    testmethod static void testproductionspecitem(){
      /*  Production_Spec_Template__c testPST=new Production_Spec_Template__c(Name='PST0001');
        insert testPST;
        Production_Spec_Item__c testPSI=new Production_Spec_Item__c(Name='TestPSI0001',Production_Spec_Template__c=testPST.Id);
        insert testPSI;
        
        ProductionSpecItemsController pspsc=new ProductionSpecItemsController();
        pspsc.CreateNewSpecItem();
        pspsc.deletemethod();
        pspsc.editmethod();
        */
        }
       
}