//@istest
public class TestcustomSettingsInroPg{
/*static testmethod void testclass(){
  
        Job_Number_Settings__c var_JNoSetng = new Job_Number_Settings__c(Name='shashi1', Auto__c='Auto123',Type__c='Auto');
        insert var_JNoSetng;
        
        NotesFiles__c  NF = new NotesFiles__c (Name = 'Profiles',Profiles__c = 'System Administrator' );
        insert NF;
         
        customSettingsInroPg tct = new customSettingsInroPg();

        var_JNoSetng.Date__c = 'mm-dd-yy';
        var_JNoSetng.Type__c = 'Date';
        update var_JNoSetng;
        customSettingsInroPg tct2 = new customSettingsInroPg();

        var_JNoSetng.Code__c='Client';
        var_JNoSetng.Type__c='Code';
        update var_JNoSetng;
        customSettingsInroPg tct3 = new customSettingsInroPg();
        
        tct.savePage();

        delete var_JNoSetng;
        string str_DateForm = 'yy';
        string str_Code = 'Client';
        tct.savePage();
        tct.cancelPage();    
         
         
        }*/
  }