//@isTest
Public class TestDisplayMaterialUsageController{

/*Static testMethod void TestDisplayMaterialUsageController()
     {
            Material_Item__c  testI=new Material_Item__c (name='test 123');
            insert testI;
            Material_Usage_line_item__c  Tmuli= new Material_Usage_line_item__c (Material_Item__c=testI.id,Qty_On_Hand__c=100);
            insert Tmuli;
                    
            ApexPages.currentPage().getParameters().put('id',testI.Id);
         // Instantiate the extention instance with the Custom Controller
           DisplayMaterialUsageController ext1=new DisplayMaterialUsageController ();
          
            // Invoke the primary method on the extension
           ApexPages.PageReference result1=ext1.createMU();
           
           ext1.strMU = Tmuli.Id;
           result1 = ext1.deleteMU();
      } 
     // End of test Method


*/
}