//isTest
public class TestVendordetailSwitchExt {
	/*static testmethod void TestVendordetailSwitchExt (){
 
           Vendor__c testVendor=new Vendor__c(Name='Test Vendor9901',Email__c='abc@gmail.com',Zip__c='12345');
           insert testVendor;
        
          Vendor_Contact__c testVC=new Vendor_Contact__c(Vendor__c=testVendor.Id,First_Name__c='Tom',Last_Name__c='Cruise',Email__c='abcde9@gmail.com');
          insert testVC;
        
    ApexPages.StandardController con = new ApexPages.StandardController(testVC);
     VendordetailSwitchExt ext=new VendordetailSwitchExt(con);
     ext.Venlistview();
 }*/

}