@isTest
public class Test_NewJobSpecUnderJobSwitchpageExt {
    static TestMethod void Test_NewJobSpecUnderJobSwitchpageExt (){
     /*   Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        NewJobSpecUnderJobSwitchpageExt controller = new NewJobSpecUnderJobSwitchpageExt(new ApexPages.StandardController(testJob1));
        boolean x = controller.isMobile;*/
    }
}