@isTest
public class TestQuoteVendorViewSwitchExt {
	static TestMethod void TestQuoteVendorViewSwitchExt(){
      /*  job__c job=new job__c(Name='testjob');
        insert job;
        Vendor__c ven=new Vendor__c(name='vendor');
        insert ven;
        Quote__c testQ=new Quote__c(name='quote',job__c=job.id);
        insert testQ;
        Vendor_Quote__c testVQSpec=new Vendor_Quote__c(Vendor__c=ven.id,Quote__c=testQ.id);
        insert testVQSpec;
       
        QuoteVendorViewSwitchExt controller = new QuoteVendorViewSwitchExt(new ApexPages.StandardController(testVQSpec));
       // boolean x = controller.isMobile;
       controller.pagedir();*/
    }
}