//@isTest
public class TestEditTagSwitchExt {
	/*static TestMethod void TestEditTagSwitchExt(){
        
        Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;

        Tag__c testtag=new Tag__c(Name='tags',Job__c=testJob1.id);
        insert testtag;
        EditTagSwitchExt controller = new EditTagSwitchExt(new ApexPages.StandardController(testtag));
	}*/
}