//@isTest
public class TestMIcreatenewnoteExtensions {
	// Test Coverage 
    /*    static testMethod void TestCampaigncreatenewnoteLightningExt()
        {
             Material_Item__c  testI=new Material_Item__c (name='test 123',Calc_Unit__c ='Size');
  		  insert testI;
               // Instantiate the standard controller with the Job
               
               ApexPages.StandardController con=new ApexPages.StandardController(testI);
                   
               ApexPages.currentPage().getParameters().put('Id', testI.Id);
               
               // Instantiate the extention instance with the standard controller 
               
               MIcreatenewnoteExtensions ext= new MIcreatenewnoteExtensions(con);
               
               test.startTest();
               
               ext.getmynote();
               
               // Invoke the primary method on the extension
               
               Pagereference pg=ext.SaveNote();
               
               Pagereference pg1=ext.cancelme();
               
               test.stopTest();
        }*/
    // End Test Coverage
}