@isTest
public class TestClientdetailSwitchExt {
    
    @isTest static void TestClientDetailPage(){
        
     /*   Client__c testAcc2=new Client__c(Name='Test Account 1');
             try
             {
                 insert testAcc2;
                 System.debug('Client inserted successfully@@@ '+testAcc2);
             }
             catch(System.DMLException e)
             {
                 System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
             }
         Client_Contact__c testCon=new Client_Contact__c(First_Name__c='Test',Last_Name__c='Contact 1',Client__c=testAcc2.Id,Email__c='testUserSFDC@yahoo.com',UserName__c='testUserSFDC@yahoo.com');
             try
             {
                 insert testCon;
                 System.debug('Client Contact inserted successfully@@@ '+testCon);
             }
             catch(System.DMLException e)
             {
                 System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION',e.getDmlStatusCode(0));
             }
        
        ClientdetailSwitchExt  con=new ClientdetailSwitchExt(new ApexPages.StandardController (testCon));
          con.Clientlistview();
        boolean x=con.isLtng;*/
    }

}