@isTest
public class Test_SpecItemExtension{
/*
static testMethod void Test_SpecItemExtension()
    {
         Specification_Template__c testST1=new Specification_Template__c(Name='Testing Specification Template');
         try
         {
            insert testST1;
            System.debug('Specification Template record inserted successfully@@@ '+testST1);
         }
         catch(System.DMLException e)
         {
            System.assert(e.getMessage().contains('Spec Item with same name Exists'));
         }
         
         Spec_Item__c testSPI1=new Spec_Item__c();
     //    insert testSPI1;
         
        ApexPages.currentPage().getParameters().put('Parentid',testST1.id);
        
         // Instantiate the standard controller with the Spec Item 
        ApexPages.StandardController con=new ApexPages.StandardController(testSPI1);
        
        // Instantiate the extention instance with the standardcontroller 
        SpecItemExtension ext=new SpecItemExtension(con);
        
        // Invoke the primary method on the extension 
        ApexPages.PageReference result=ext.saveme();
        
        delete testSPI1;
        result=ext.saveme();
     }*/
     }