@isTest
public class TestMediaTypeListviewSwitchExt {
    
     static testmethod void testMTlistView(){
        /*  Media_Type__c testMedia=new Media_Type__c(Name='MT012');
          insert testMedia;
         MediaTypeListviewSwitchExt mListCon=new MediaTypeListviewSwitchExt(new Apexpages.standardController(testMedia));
           Apexpages.pagereference result=mListCon.Mtlistview();*/
          
}
}