@isTest
public class TestEstimateViewFromPoSwitchExt {
	static testmethod void TestEstimateViewFromPoSwitchExt (){
 		/*Job__c job=new Job__c(name='job');
        insert job;
        Purchase_Order__c po=new Purchase_Order__c(name='po',job__c=job.id);
        insert po;
     ApexPages.StandardController con = new ApexPages.StandardController(po);
     EstimateViewFromPoSwitchExt ext=new EstimateViewFromPoSwitchExt(con);
           ext.EstviewFromPO();
           
*/ 
 }
}