@isTest
public class TestEditScheduleTemplateSwitchExt {

  /*  testmethod static void testEditScheTemp(){
         Media_Type__c testMedia=new Media_Type__c(Name='MT012');
          insert testMedia;
       
          Schedule_Template__c testST=new Schedule_Template__c(Name='ST012',Media_Types__c=testMedia.Id);
          insert testST;
        EditScheduleTemplateSwitchExt edsctp=new EditScheduleTemplateSwitchExt(new Apexpages.standardController (testST));
        
    }*/
}