//@isTest
Public class TestCreateMaterialUsageExtension{
/*static testMethod void TestCreateMaterialUsageExtension(){

    Material_Item__c  testI=new Material_Item__c (name='test 123',Calc_Unit__c ='Size');
    insert testI;
    Material_Usage_line_item__c  Tmuli= new Material_Usage_line_item__c (Material_Item__c=testI.id,Qty_On_Hand__c=100);
    insert Tmuli;
    Material_Usage_line_item__c  muli= new Material_Usage_line_item__c (Material_Item__c=testI.id);
    
    
    ApexPages.currentPage().getParameters().put('materialid',testI.Id);
    ApexPages.StandardController con=new ApexPages.StandardController(muli);
     
           // Instantiate the extention instance with the standard controller
           CreateMaterialUsageExtension ext =new CreateMaterialUsageExtension(con);
    ApexPages.PageReference result1=ext.saveme();
    ApexPages.PageReference result2=ext.cancelme();
    

}
static testMethod void TestCreateMaterialUsageExtension1(){

    Material_Item__c  testI=new Material_Item__c (name='test 123',Calc_Unit__c ='Sheet');
    insert testI;
    Material_Usage_line_item__c  Tmuli= new Material_Usage_line_item__c (Material_Item__c=testI.id,Qty_On_Hand__c=100);
    insert Tmuli;
    Material_Usage_line_item__c  muli= new Material_Usage_line_item__c (Material_Item__c=testI.id);
    
    
    ApexPages.currentPage().getParameters().put('materialid',testI.Id);
    ApexPages.StandardController con=new ApexPages.StandardController(muli);
     
           // Instantiate the extention instance with the standard controller
           CreateMaterialUsageExtension ext =new CreateMaterialUsageExtension(con);
    ApexPages.PageReference result1=ext.saveme();
    ApexPages.PageReference result2=ext.cancelme();
    

}

static testMethod void TestCreateMaterialUsageExtension2(){

    Material_Item__c  testI=new Material_Item__c (name='test 123',Calc_Unit__c ='Each');
    insert testI;
    Material_Usage_line_item__c  Tmuli= new Material_Usage_line_item__c (Material_Item__c=testI.id,Qty_On_Hand__c=100);
    insert Tmuli;
    Material_Usage_line_item__c  muli= new Material_Usage_line_item__c (Material_Item__c=testI.id);
    
    
    ApexPages.currentPage().getParameters().put('materialid',testI.Id);
    ApexPages.StandardController con=new ApexPages.StandardController(muli);
     
           // Instantiate the extention instance with the standard controller
           CreateMaterialUsageExtension ext =new CreateMaterialUsageExtension(con);
    ApexPages.PageReference result1=ext.saveme();
    ApexPages.PageReference result2=ext.cancelme();
    

}*/

}