//@isTest
public class TestUnapproveELI {
	/*static TestMethod void TestUnapproveELI  (){
        job__c job=new job__c(Name='testjob');
        insert job;
        Estimate_Line_Items__c testEst=new Estimate_Line_Items__c(name='Est',job__c=job.id,Quantity__c=10,Amount__c=100);
        insert testEst;
         Estimate_Line_Items__c testEst2=new Estimate_Line_Items__c(name='Est1',job__c=job.id,Quantity__c=10,Amount__c=500);
        insert testEst2;
        Apexpages.currentPage().getParameters().put('id',testEst.id);
        UnapproveELI controller = new UnapproveELI (new ApexPages.StandardController(testEst));
       controller.autoRun();
    }*/
}