//@isTest
Public Class TestDisplayBillboardContractController{

/*static testMethod void TestDisplayBillboardContractController()
     {
            
          Client__c testClient=new Client__c(Name='Client 623');
           insert testClient; 
          Vendor__c testvendor=new Vendor__c (Name='Vendor 623',Vendor_Type__c ='Outdoor');
           insert testvendor; 
   
          Billboard__c  testI=new Billboard__c(Client_Name__c=testClient.Id,name='test 123',BB_Vendor__c=testvendor.id);
            insert testI;
           
          Billboard_Contract__c bbc=new Billboard_Contract__c(Billboard__c=testI.id,BB_Vendor_Name__c=testvendor.id);
            insert bbc;
           
           
            
            ApexPages.currentPage().getParameters().put('id',testI.Id);
         // Instantiate the extention instance with the Custom Controller
           DisplayBillboardContractController ext1=new DisplayBillboardContractController();
          
            // Invoke the primary method on the extension
           ApexPages.PageReference result1=ext1.createBBC();
           
           ext1.strBBC= bbc.Id;
           result1 = ext1.deleteBBC();
      } 
     // End of test Method
*/

}