@isTest

Public Class TestDisplayCreativeBriefSpecItemsCon{
 
 Static testMethod Void TestDisplayCreativeBriefSpecItemsCon(){
 
       /*  Specification_Template__c testST1=new Specification_Template__c(Name='Testing Specification Template');
         try
         {
            insert testST1;
            System.debug('Specification Template record inserted successfully@@@ '+testST1);
         }
         catch(System.DMLException e)
         {
            System.assert(e.getMessage().contains('Spec Item with same name Exists'));
         }
         
         Spec_Item__c testSPI1=new Spec_Item__c(Name='Test Spec Item 1',Specification_Template__c=testST1.Id);
 
           INSERT testSPI1;
 
         DisplayCreativeBriefSpecItemsController CON=NEW DisplayCreativeBriefSpecItemsController();
         con.createSpecitems();
         con.save();
         con.cancelme();*/
 
 }

}