@isTest
public class TestPOViewSwitchExt {
	static TestMethod void TestPOViewSwitchExt(){
     /*   job__c job=new job__c(Name='testjob');
        insert job;
        Purchase_Order__c PO=new Purchase_Order__c(name='PO',job__c=job.id);
        insert PO;
       
        POViewSwitchExt controller = new POViewSwitchExt (new ApexPages.StandardController(PO));
       // boolean x = controller.isMobile;
       controller.pagedir();*/
    }
}