@isTest
Public class TestCreateInvAllocTempLItemExt {
static testMethod void TestCreateInvAllocTempLItemExt (){

  /*
           Client__c client= new Client__c(name='test', client_code__c='123');
           insert client;
           
          Invoice_Allocation_Template__c TestIAT=new Invoice_Allocation_Template__c(Name='Test IAT');
            Insert TestIAT;
          
          Invoice_Allocation_Template_Line_Item__c  testIATLI =new  Invoice_Allocation_Template_Line_Item__c  (Invoice_Allocation_Template__c=TestIAT.id);
              
            
           ApexPages.currentPage().getParameters().put('IATID',TestIAT.Id);
           ApexPages.StandardController con=new ApexPages.StandardController(testIATLI );
     
           // Instantiate the extention instance with the standard controller
           CreateInvAllocTempLItemExt ext =new CreateInvAllocTempLItemExt(con);
        
           // Invoke the primary method on the extension 
           ApexPages.PageReference result1=ext.saveme();
           ApexPages.PageReference result2=ext.cancelme();
           ApexPages.PageReference result3=ext.savenew(); 
          
            List<SelectOption> Codes=ext.getClients();
           string result4=ext.getClientName();
           ext.SetClientName('Test234'); 
           
         
*/
}



}