@isTest
Public class TestCreateNewBillboardExtension {
/*static testMethod void TestCreateNewBillboardExtension (){

  Job_Number_Setting__c customSetting994 = new  Job_Number_Setting__c(Name= 'yy');
           insert customSetting994;
            
             
               
           Client__c testClient=new Client__c(Name='Test client');
           insert testClient; 
           Vendor__c testvendor=new Vendor__c (Name='Test vendor',Vendor_Type__c ='Outdoor');
           insert testvendor; 
   
           Billboard__c  testI=new Billboard__c(Client_Name__c=testClient.Id,name='test 123',BB_Vendor__c=testvendor.id);

           
           ApexPages.StandardController con=new ApexPages.StandardController(testI);
     
           // Instantiate the extention instance with the standard controller
           CreateNewBillboardExtension ext =new CreateNewBillboardExtension(con);
        
           // Invoke the primary method on the extension 
           ApexPages.PageReference result1=ext.saveme();
           ApexPages.PageReference result2=ext.cancel();
           List<SelectOption> clients=ext.getClients();
           List<SelectOption> vendors=ext.getVendors();
           string result4=ext.getVendorName();
           string result5=ext.getClientName();
           ext.ClientName='Test client';
           ext.SEtVendorName('Test vendor');
            
       

}
*/


}