//@isTest
public class TesteditGLCodeSwitchExt {
    
  /*  @isTest static void glEditTestMethod(){
        GL_Department__c gldep=new GL_Department__c(Name='Test GL Department',GL_Dept_Code__c='123456');
        insert gldep;
        GL_Code__c glcode=new GL_Code__c(name='GL Code Test',GL_ID__c='111907',GL_Department__c=gldep.id,Unit_Type__c='Days',Unit_Cost__c=100);
         insert glcode;        
         editGLCodeSwitchExt glCodeCon=new editGLCodeSwitchExt(new ApexPages.StandardController(glcode));
        }*/
}