@isTest
Public class TestCreateInvAllocationTempExt {
static testMethod void TestCreateInvAllocationTempExt (){

         /* Invoice_Allocation_Template__c TestIAT=new Invoice_Allocation_Template__c(Name='Test IAT');
          ApexPages.StandardController con=new ApexPages.StandardController(TestIAT);
     
           // Instantiate the extention instance with the standard controller
           CreateInvAllocationTempExt ext =new CreateInvAllocationTempExt(con);
        
           // Invoke the primary method on the extension 
           ApexPages.PageReference result1=ext.saveme();
           ApexPages.PageReference result2=ext.cancelme();*/
      
}



}