//@isTest
Public Class TestDisplayPOLIWhenPOStatusIsSent{
/*
// Test Method 
    static testMethod void TestDisplayPOLIWhenPOStatusIsSent()
    {
         PO_Line_Item__c POLI = new PO_Line_Item__c();
         
          // Instantiate the standard controller with the Purchase Order Line Item
         
         ApexPages.StandardController con=new ApexPages.StandardController(POLI);
         
           // Instantiate the extention instance with the standard controller
         
         DisplayPOLIWhenPOStatusIsSent ext=new DisplayPOLIWhenPOStatusIsSent(con);
         
         System.assertEquals(POLI.id,ext.theID);
    } // End of test Method*/
}