//@isTest
public class TestCampaignViewNote {
    /*  static testMethod void Test_JobViewNote()
    {
         Campaign__c  testI=new Campaign__c(name='test 123');
           insert testI;
               
          System.assertEquals('test 123',testI.Name);  
          
          Note n=new Note(parentId=testI.Id,Title='Test Title 852',IsPrivate=True,Body='Test Note Body');
               insert n;
              
          ApexPages.StandardController con=new ApexPages.StandardController(testI);
                   
          ApexPages.currentPage().getParameters().put('Id', n.Id);
               
          CampaignViewNote ext= new CampaignViewNote(con);
          ApexPages.Pagereference result1=ext.Cancel();
          result1=ext.editNote();
          result1=ext.deleteNote();
     }*/
}