@isTest
public class TestEstimateSwitchExt {
	/* static TestMethod void TestEstimateSwitchExt(){
        Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        Estimate_Line_Items__c testEst=new Estimate_Line_Items__c(Name='Camp',Job__c=testJob1.id);
        insert testEst;
        EstimateSwitchExt controller = new EstimateSwitchExt(new ApexPages.StandardController(testEst));
      //  boolean x = controller.isMobile;
}*/
}