@isTest
public class TestUserRoleExtension {
   /*  static testMethod void UserRoleTest()
    {   
            
            UserRole u=new UserRole(Name='Designer123');
          //  insert u;
        
            // Instantiate the extention instance with the standard controller
              ApexPages.StandardController con=new ApexPages.StandardController(u);

              UserRoleExtension  ext=new UserRoleExtension(con);
        
            // Invoke the saveme method on the extension
                ApexPages.PageReference result1=ext.Save();
                result1=ext.cancelme();
                
                System.assertEquals('Designer123',u.Name);
                
                UserRole u1=new UserRole();
            
                // Instantiate the extention instance with the standard controller 
                ApexPages.StandardController con1=new ApexPages.StandardController(u1);

                UserRoleExtension  ext1=new UserRoleExtension(con1);
                
                // Invoke the saveme method on the extension 
                try
                {
                    ApexPages.PageReference result2=ext.Save();
                 }
                 catch(System.DMLException e)
                 {
                      System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION' , e.getDmlStatusCode(0));
                 }   
     }*/
}