//@isTest
public class Test_JobsTabExt {
   /* static TestMethod void Test_JobsTabExt(){
        List<Job__c> lstjobs=new List<Job__c>();
		Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        lstjobs.add(testJob1);
        Job__c testJob2=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob2;
        lstjobs.add(testJob2);
        JobsTabExt controller = new JobsTabExt(new ApexPages.StandardSetController(lstjobs));
        controller.isLtng=true;
        Apexpages.pagereference p=controller.Joblistview();
        //controller.NewMethod();
        //controller.getStatusList();
        //controller.getpopulateJobList();
        //controller.beginning();
        //controller.previous();
        //controller.next();
        //controller.end();
        //controller.getprev();
        //controller.getnxt();
        //controller.setIndex();
    }*/
}