@isTest
public class TestDisplayTasksInRoleCalendar {
	/*   static testMethod void displayTaskInRoleCal()
       {
            UserRole ur=new UserRole(Name='Test Role 995');
            insert ur;
              
            System.assertEquals('Test Role 995',ur.Name);
            
            ApexPages.currentPage().getParameters().put('id',ur.id);
            
             // Instantiate the standard controller with the Role
            ApexPages.StandardController con=new ApexPages.StandardController(ur);    
            
             // Instantiate the extention instance with the standardcontroller
            DisplayTasksInRoleCalendar ext=new DisplayTasksInRoleCalendar(con);
            
            // Invoke the primary method on the extension
            ApexPages.Pagereference result=ext.roleCalendarTask();
            
            result=ext.RolesView();
            result=ext.EditRole();
            result=ext.DeleteRole();
        }*/
}