@isTest
public class TestEditQuoteSwitchExt {
	 static TestMethod void TestEditQuoteSwitchExt(){
       /* Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        Quote__c testQ=new Quote__c(Name='Camp',Job__c=testJob1.id);
        insert testQ;
        EditQuoteSwitchExt controller = new EditQuoteSwitchExt(new ApexPages.StandardController(testQ));
      //  boolean x = controller.isMobile;*/
}
}