//@isTest
public class TestDeleteMIAttachmentExtension {
	// Test Coverage 
   /*     static testMethod void TestDeleteMIAttachmentExtension()
        {
           Material_Item__c  testI=new Material_Item__c (name='test 123',Calc_Unit__c ='Size');
  		        insert testI;
           System.assertEquals('test 123',testI.Name);
               
           Blob b = Blob.valueOf('Hello');

           Attachment a=new Attachment(parentId=testI.Id,Name='Test File',Body=b);
           
               insert a;
               
        // Instantiate the standard controller with the Job 
           ApexPages.StandardController con=new ApexPages.StandardController(a);
           ApexPages.currentPage().getParameters().put('Id', a.Id);
        
        // Instantiate the extention instance with the standardcontroller
           DeleteMIAttachmentExtension ext=new DeleteMIAttachmentExtension(con);
        
        // Invoke the Delete method 
           ApexPages.Pagereference result=ext.checkDelete();
        
        // The below line covers the catch block in checkDetele method 
           ApexPages.Pagereference result1=ext.checkDelete();
     }*/
    // End of Test Coverage
}