@isTest
Public Class TestClientViewPageExt {

 static testmethod void TestClientViewPageExt (){
 
  /* Client__c c=new Client__c(name='test');
   insert c;
   
    Billboard__c  testI=new Billboard__c(Client_Name__c=c.Id,name='test 123');
    insert testI;
   
    ApexPages.StandardController con = new ApexPages.StandardController(c);
     ClientViewPageExt ext=new ClientViewPageExt(con);
      */     
           
 
 }

}