@isTest
public class Test_TSEntryTabExt {
	static TestMethod void Test_TSEntryTabExt(){
	/*	Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        List<Job__c> jobList = new List<Job__c>();
        insert testJob1;
        jobList.add(testJob1);
        TSEntryTabExt controller = new TSEntryTabExt(new ApexPages.StandardSetController(jobList));
		controller.getTsEnty();
        controller.beginning();
        controller.end();
        controller.getnxt();
        controller.getprev();
        controller.NewMethod();
        controller.previous();
        */
    }
}