@isTest
public class TestCampaignTabOverrideExt {
	static TestMethod void TestCampaignTabOverrideExt  (){
      /*  Campaign__c testCamp=new Campaign__c(Name='Camp');
        insert testCamp;
        CampaignTabOverrideExt controller = new CampaignTabOverrideExt (new ApexPages.StandardController(testCamp));
       // boolean x = controller.isMobile;
        boolean x=controller.isLtng;
        controller.campaignsview();*/
}
}