@istest
Public class TestEditInvAllocationTempExt{

static testMethod void TestEditInvAllocationTempExt()
      {
        /*   Invoice_Allocation_Template__c   testIAl=new Invoice_Allocation_Template__c  (Name='Test Name');
          insert testIAl;
         
          
           Invoice_Allocation_Template__c    testBB = [Select id,name from Invoice_Allocation_Template__c    where id =:testIAl.Id];
         
             // Instantiate the standard controller with the Client
          ApexPages.StandardController con = new ApexPages.StandardController(testBB);
           ApexPages.CurrentPage().getParameters().put('id',testBB.id);
            // Instantiate the extention instance with the standardcontroller
          
          EditInvAllocationTempExt ext = new EditInvAllocationTempExt(con);
        
        // Invoke the primary method on the extension */
        //  ApexPages.PageReference result1=ext.saveme();
         // ApexPages.PageReference result2=ext.cancelme();
          
         
          
     }// End of Test Coverage


}