@istest
public class TestActiveJobsByUserDashboardExt {
    @istest static void TestActiveJobsByUserDashBoard(){
        
      /*   job__c job=new job__c(Name='testjob',Status__c='Active');
        insert job;
        ActiveJobsByUserDashboardExt ext=new ActiveJobsByUserDashboardExt(new Apexpages.StandardController(job));
         ext.beginning();
         ext.end();
        ext.getnxt();
        ext.getprev();
        ext.getJobs();
        ext.next();
        ext.previous();
        */
        
    }
    

}