//@isTest
Public Class TestDisplayClientInvUnderClientDetail{
 /*static testMethod void TestDisplayClientInvUnderClientDetail()
    {
           Client__c a = new Client__c();
            //Job__c testJob1=new Job__c(Name='Job011',Start_Date__c=System.Today(),Media_Types__c='test',Schedule_Template__c='test',Specification_Template__c='Test1',Campaign__c=testCampaign1.id,JS_Client__c=a.id,JS_Client_Contact__c=c.id,Schedule_Calc__c='Start Date');
           
             // Instantiate the extention instance with the Custom Controller
         
           DisplayClientInvoiceUnderClientDetail ext=new DisplayClientInvoiceUnderClientDetail();
           
           DisplayClientInvoiceUnderClientDetail ext1=new DisplayClientInvoiceUnderClientDetail();
           
           
           
           System.assertEquals(a.id,ext1.theID);      
    } */
     // End of test Method 

}