//@isTest
Public Class TestDisplayBillboardInvoiceController{

/*static testMethod void TestDisplayBillboardInvoiceController()
     {
            
          Client__c testClient=new Client__c(Name='Client 623');
           insert testClient; 
          Vendor__c testvendor=new Vendor__c (Name='Vendor 623',Vendor_Type__c ='Outdoor');
           insert testvendor; 
   
          Billboard__c  testI=new Billboard__c(Client_Name__c=testClient.Id,name='test 123',BB_Vendor__c=testvendor.id);
            insert testI;
           
          Billboard_Invoice__c bbi=new Billboard_Invoice__c(Billboard__c=testI.id);
            insert bbi;
           
           
            
            ApexPages.currentPage().getParameters().put('id',testI.Id);
         // Instantiate the extention instance with the Custom Controller
           DisplayBillboardInvoiceController ext1=new DisplayBillboardInvoiceController();
          
            // Invoke the primary method on the extension
           ApexPages.PageReference result1=ext1.createBBI();
           
           ext1.strBBI= bbi.Id;
           result1 = ext1.deleteBBI();
      } 
     // End of test Method

*/
}