@isTest
public class Test_EditJobTaskSwitchPageExtension {
/*	static TestMethod void Test_EditJobTaskSwitchPageExtension(){
		Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        EditJobTaskSwitchPageExtension controller = new EditJobTaskSwitchPageExtension(new ApexPages.StandardController(testJob1));
        boolean x = controller.isMobile;
        boolean y = controller.isLight;
        
        
    }*/
}