@isTest

Public Class TestSforceTaskDetailPageExt{
    Public  Static testMethod void TestSforceTaskDetailPageExt(){
        
        
        /*
        Task  t=new Task  ( subject='email',status='closed');
        insert t;
        
        ApexPages.currentPage().getParameters().put('Id',t.Id);
        
        ApexPages.StandardController con = new ApexPages.StandardController(t);
        
        // Instantiate the extention instance with the standardcontroller
        SforceTaskDetailPageExt ext = new SforceTaskDetailPageExt(con);
        ext.back();
        ext.SendReplayMethod();
        //ext.sendmail();
        ext.del();
        
        */
    }
    
    
}