//isTest
public class TestVendorContactsRelatedListUnderVendor {
 /*   
    @isTest static void VendorContactsUnderVendor(){
        
           Vendor__c testVendor=new Vendor__c(Name='Test Vendor9901',Email__c='abc@gmail.com',Zip__c='12345');
           insert testVendor;
        
         Vendor_Contact__c testVC=new Vendor_Contact__c(Vendor__c=testVendor.Id,First_Name__c='Tom',Last_Name__c='Cruise',Email__c='abcde9@gmail.com');
          insert testVC;
        
          VendorContactsRelatedListUnderVendor VednorCont=new VendorContactsRelatedListUnderVendor();
          VednorCont.CreateQuote();
         boolean x=VednorCont.isLtng;
         boolean y= VednorCont.isMob;
        
          
        
        
    }*/
    
}