@isTest
public class Test_JobTeamAddEditStaffSwitchPage  {
    static TestMethod void Test_JobTeamAddEditStaffSwitchPage  (){
      /*  Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        JobTeamAddEditStaffSwitchExt controller = new JobTeamAddEditStaffSwitchExt (new ApexPages.StandardController(testJob1));
        boolean x = controller.isMobile;*/
    }
}