//@isTest
public class TestEditEstimateSwitchExt {
	 /*static TestMethod void TestEditEstimateSwitchExt(){
        Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        Estimate_Line_Items__c testEst=new Estimate_Line_Items__c(Name='Camp',Job__c=testJob1.id);
        insert testEst;
        EditEstimateSwitchExt controller = new EditEstimateSwitchExt(new ApexPages.StandardController(testEst));
      //  boolean x = controller.isMobile;
}*/
}