@isTest
Public class TestInvAllocationTempEnhancedListExt{

static Testmethod Void TestInvAllocationTempEnhancedListExt(){
    
     /*  Test.StartTest();
        
        
           Client__c client= new Client__c(name='test', client_code__c='123');
           insert client;
           
          Invoice_Allocation_Template__c TestIAT=new Invoice_Allocation_Template__c(Name='Test IAT');
            Insert TestIAT;
        
       
        
        ApexPages.currentPage().getParameters().put('strIAT',TestIAT.Id);
        ApexPages.StandardController con=new ApexPages.StandardController(TestIAT);    
        InvAllocationTempEnhancedListExt ext = new InvAllocationTempEnhancedListExt(con);
        
        ApexPages.Pagereference result1 = ext.editIAT();
        
        result1 = ext.deleteIAT();
        
        result1 = ext.createNewIAt();
        
        Test.StopTest();*/
        
    }// End of Test Coverage code       


}