@isTest
public class TestClientContactsRelatedListUnderClient {
    
    @istest static void TestClientContactsUnderClient(){
      /*  
        Client__c TestClnt=new Client__c(Name='Test Cllient',Active__c=true);
        insert TestClnt;
        
     Client_Contact__c testCC = new Client_Contact__c(First_Name__c='Test Client', Last_Name__c='Contact' ,Name = 'Test Client Contact', Client__c=TestClnt.id,Email__c='testClientContact9897@SFDC.com');     
        insert testCC;
        
        ClientContactsRelatedListUnderClient clientc=new ClientContactsRelatedListUnderClient();
        
       
       clientc.CreateQuote();
        clientc.ViewAll();
        clientc.Showless();
        boolean x=clientc.isLtng;
        boolean y=clientc.isMob;
       */
        
    }  

}