@isTest
public class TestSpecViewSwitchExt {
	static TestMethod void TestSpecViewSwitchExt  (){
       /* job__c job=new job__c(Name='testjob');
        insert job;
        Job_Spec__c testSpec=new Job_Spec__c(Name='Camp',job__c=job.id);
        insert testSpec;
        SpecViewSwitchExt controller = new SpecViewSwitchExt (new ApexPages.StandardController(testSpec));
       // boolean x = controller.isMobile;
       controller.pagedir();*/
}
}