//@istest
Public class TestDeleteBillboard{

/*static testMethod void TestDeleteBillboard()
      {
           Client__c testClient=new Client__c(Name='Test client');
           insert testClient; 
           Vendor__c testvendor=new Vendor__c (Name='Test vendor',Vendor_Type__c ='Outdoor');
           insert testvendor; 
   
           Billboard__c  testI=new Billboard__c(Client_Name__c=testClient.Id,name='test 123',BB_Vendor__c=testvendor.id);
           insert testI;
          System.assertEquals('test 123',testI.Name);
          
          ApexPages.CurrentPage().getParameters().put('id',testI.id);
         
             // Instantiate the standard controller with the Client
          ApexPages.StandardController con = new ApexPages.StandardController(testI);
        
            // Instantiate the extention instance with the standardcontroller
          DeleteBillboard ext = new DeleteBillboard(con);
        
        // ext.isError = True;          
            // Invoke the Delete method on the extension
          ApexPages.PageReference result = ext.CheckDelete();
          
        
          result = ext.CheckDelete();
          
     }// End of Test Coverage
*/

}