@isTest
public class Test_TimesheetEntriesExt {
    
	static TestMethod void Test_TimesheetEntriesExt(){
      
       /* 
		Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        job_Task__c jTask = new Job_Task__c(Job__c = testJob1.id);
        insert jTask;
        Timesheet_Entries__c t = new Timesheet_Entries__c(Date__c = date.valueOf('2016-10-01 09:09:09') ,Job__c=testJob1.id,Start_Watch__c=datetime.valueOf('2016-11-11 11:11:11'), End_Watch__c=datetime.valueOf('2016-11-11 11:11:11'));
        
        TimesheetEntriesExt controller = new TimesheetEntriesExt(new ApexPages.StandardController(t));
        controller.objTSDetail = t;
        string x = controller.calcTimeDiff;
        boolean y = controller.error;
        controller.isMobile = false;
        controller.jobId = testJob1.id;
        controller.getJobName();
        
        controller.Cancel();
        controller.End();
        controller.getGLCodeOfTask();
        controller.getRemainHours();
        controller.getTaskName();
        controller.getTotalHours();
        controller.Save();
        controller.start();
        
        
        controller.objTSDetail = t;
        controller.JobNameStr = testJob1.id;
        controller.JobTaskNameStr = jTask.id;
        controller.ShowProductionEstimate = true;
        controller.Save();
        controller.getGLCodeOfTask();
        
        controller.isMobile = true;
        controller.Cancel();*/
    }

}