@isTest
public class TestQuoteSwitchExt {
	 static TestMethod void TestQuoteSwitchExt(){
    /*    Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        Quote__c testQ=new Quote__c(Name='Camp',Job__c=testJob1.id);
        insert testQ;
        QuoteSwitchExt controller = new QuoteSwitchExt(new ApexPages.StandardController(testQ));
      //  boolean x = controller.isMobile;*/
}
}