//@istest
public class TestEditProductionSpecItemSwitchExt {

  /*  @isTest static void testEditProduSpec(){
        
        Production_Spec_Template__c testPST=new Production_Spec_Template__c(Name='Testing Production Spec Template 0001');
        insert testPST;
        
        EditProductionSpecItemSwitchExt editProSC=new EditProductionSpecItemSwitchExt(new Apexpages.standardController(testPST));
         
        
    }*/
}