@isTest
public class TestEditJobSpecUnderJobSwitchpageExt {
	/* static TestMethod void TestEditJobSpecUnderJobSwitchpageExt(){
        Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;         
        Job_Spec__c testSpec=new Job_Spec__c(Name='Camp',Job__c=testJob1.id);
        insert testSpec;
        EditJobSpecUnderJobSwitchpageExt controller = new EditJobSpecUnderJobSwitchpageExt (new ApexPages.StandardController(testSpec));
        boolean x = controller.isMobile;
}*/
}