//@isTest
Public class TestDisplayBBInvoiceUnderVendor{

 /*static testMethod void TestDisplayBBInvoiceUnderVendor()
    {
           Vendor__c a = new Vendor__c ();
            
           DisplayBBInvoiceUnderVendor ext=new DisplayBBInvoiceUnderVendor();
           
           DisplayBBInvoiceUnderVendor ext1=new DisplayBBInvoiceUnderVendor();
           
           
           
           System.assertEquals(a.id,ext1.theID);      
    } */
     // End of test Method 

}