@isTest
public class TestDeletePESpecItemExt {
	static testmethod void TestDeletePESpecItemExt(){
 	/*Material_Item__c mm=new Material_Item__c(name='material item');
    insert mm;    
        
      Production_Estimate_Template__c testPST=new Production_Estimate_Template__c(Name='PST0001');
       insert testPST;
      Production_Estimate_Temp_Line_Items__c testPSI=new Production_Estimate_Temp_Line_Items__c(Name='TestPSI0001',Production_Estimate_Template__c=testPST.Id,Material_Item__c=mm.id);
       insert testPSI;
   
     ApexPages.StandardController con = new ApexPages.StandardController(testPSI);
     DeletePESpecItemExt ext=new DeletePESpecItemExt(con);
     ext.checkDelete();*/
   }
}