@istest
Public class TestEditInvAllocTempLItemExt{

static testMethod void TestEditInvAllocTempLItemExt()
      {
          /*
          Client__c client=new Client__c(name='Test');
          insert client;
          
          Invoice_Allocation_Template__c   testIAl=new Invoice_Allocation_Template__c  (Name='Test Name');
          insert testIAl;
          
          Invoice_Allocation_Template_Line_Item__c   TestIALI=new Invoice_Allocation_Template_Line_Item__c  (Invoice_Allocation_Template__c =testIAl.id);
          insert TestIALI;
          
          
         Invoice_Allocation_Template_Line_Item__c   TestIALI1= [Select id,name,Client__c from Invoice_Allocation_Template_Line_Item__c where id =:TestIALI.Id];
         
          // Instantiate the standard controller with the Client
          ApexPages.StandardController con = new ApexPages.StandardController(TestIALI1);
          EditInvAllocTempLItemExt ext = new EditInvAllocTempLItemExt(con);
          ApexPages.PageReference result1=ext.saveme();
           ApexPages.PageReference result2=ext.cancelme();
           
            List<SelectOption> clients=ext.getclients();
           string result4=ext.getclientName();
           ext.SetclientName('Test234'); 
           */
          
          
  }
  }