@istest
Public class TestDisplayInvAllocTempLitemController{

static testMethod void TestDisplayInvAllocTempLitemController()
      {
          /* Client__c testClient=new Client__c(Name='Test client');
           insert testClient; 
          
          Client__c client=new Client__c(name='Test');
          insert client;
          
          Invoice_Allocation_Template__c   testIAl=new Invoice_Allocation_Template__c  (Name='Test Name');
          insert testIAl;
          
          Invoice_Allocation_Template_Line_Item__c   TestIALI=new Invoice_Allocation_Template_Line_Item__c  (Invoice_Allocation_Template__c =testIAl.id);
          insert TestIALI;
          
          
         Invoice_Allocation_Template_Line_Item__c   TestIALI1= [Select id,name,Client__c from Invoice_Allocation_Template_Line_Item__c where id =:TestIALI.Id];
         
         
          ApexPages.currentPage().getParameters().put('id',testIAl.Id);
    // Instantiate the extention instance with the Custom Controller
           DisplayInvAllocTempLitemController ext1=new DisplayInvAllocTempLitemController();
           
            // Invoke the primary method on the extension
           
           ApexPages.PageReference result1 = ext1.createIATLI();
           ext1.strIATLI= TestIALI.Id;
           result1 = ext1.deleteIATLI();
           result1 = ext1.EditIATLI();
           
           
           */
           
 }
 }