@isTest
public class TestJobdetailpageLightening07Extension {
    static testMethod void TestJobdetailpageLightening07Extension(){
      /*  Media_Type__c testMedia=new Media_Type__c(Name='Test Media 301');
        insert testMedia;
        Schedule_Template__c testST=new Schedule_Template__c(Name='Test Schedule Template 301',Media_Types__c=testMedia.Id);
        insert testST;
        Specification_Template__c testSpec=new Specification_Template__c(Name='Testing Spcification Template 301');
        insert testSpec;
    	Job__c testJob1=new Job__c(Name='Test Job 301',Flag__c=True,Job_Auto_Number__c='Job12347',Start_Date__c=System.Today(),Media_Types__c=testMedia.Id,Schedule_Template__c=testST.Id,Specification_Template__c=testSpec.Id);
		insert testJob1;
        
        System.assertEquals('Test Job 301',testJob1.Name);
        ApexPages.StandardController con1=new ApexPages.StandardController(testJob1);
        JobdetailpageLightening07Extension ext1=new JobdetailpageLightening07Extension(con1);
        ext1.editNotes();
        ext1.saveNotes();
        ext1.CancelNotes();
        ext1.AddStaffs();
        ext1.AddStaffsLightning();
        ext1.incrementCounter();*/
    }
}