//@isTest
public class TestDeleteMIFeedAttachmentExtension {
	// Test Coverage 
     /*   static testMethod void TestDeleteMIFeedAttachmentExtension()
        {
          Campaign__c  testC=new Campaign__c(name='test 123');
          insert testC;
            
            Material_Item__c  testI=new Material_Item__c (name='test 1234',Calc_Unit__c ='Size');
  		        insert testI;
               
           System.assertEquals('test 1234',testI.Name);
               
           Blob b = Blob.valueOf('Hello');

           FeedItem a=new FeedItem (parentId=testI.Id,Body='hello');
           
               insert a;
            
            FeedItem aa=new FeedItem (parentId=testC.Id,Body='hello');
           
               insert aa;
            
            
               
        // Instantiate the standard controller with the Job 
           ApexPages.StandardController con=new ApexPages.StandardController(a);
             System.currentPagereference().getParameters().put('Id', a.Id);
            
            ApexPages.StandardController con1=new ApexPages.StandardController(aa);
             System.currentPagereference().getParameters().put('Id', aa.Id);
        
        // Instantiate the extention instance with the standardcontroller
           DeleteMIFeedAttachmentExtension ext=new DeleteMIFeedAttachmentExtension(con);
           
        // Invoke the Delete method 
           ApexPages.Pagereference result=ext.checkDelete();
        
        // The below line covers the catch block in checkDetele method 
           ApexPages.Pagereference result1=ext.checkDelete();
            
            
           DeleteCampaignFeedAttachmentExtension ext1=new DeleteCampaignFeedAttachmentExtension(con1);
             ApexPages.Pagereference resultt=ext1.checkDelete();
     }*/
    // End of Test Coverage
}