@isTest
public class TestProductionEstTempEnhancedListExt {

    static Testmethod Void TestProductionEstTempEnhancedListExt()
    {
    /*
        Test.StartTest();
        Production_Estimate_Template__c TestIAT=new Production_Estimate_Template__c(Name='Test IAT');
        Insert TestIAT;
        
        ApexPages.currentPage().getParameters().put('strIAT',TestIAT.Id);
        ApexPages.StandardController con=new ApexPages.StandardController(TestIAT);    
        ProductionEstTempEnhancedListExt ext = new ProductionEstTempEnhancedListExt(con);
       
        ext.Peid = TestIAT.Id;
        String strPET;
        String Peid;
        ext.DelSpec();
        ext.EditPE();
        ext.NewMethod();
        Test.StopTest();
        */
    }// End of Test Coverage code       

    
    
}