@isTest
Public class TestDisplayBBdUnderVendorController{

 static testMethod void TestDisplayBillboardUnderVendorController()
    {
           
        /*   
           Client__c testClient=new Client__c(Name='Test client');
           insert testClient; 
           Vendor__c testvendor=new Vendor__c (Name='Test vendor',Vendor_Type__c ='Outdoor');
           insert testvendor; 
   
           Billboard__c  testI=new Billboard__c(Client_Name__c=testClient.Id,name='test 123',BB_Vendor__c=testvendor.id);
           insert testI;
          System.assertEquals('test 123',testI.Name);
            
           ApexPages.currentPage().getParameters().put('id',testvendor.Id); 
           DisplayBillboardUnderVendorController ext=new DisplayBillboardUnderVendorController ();
            List<SelectOption>ListStatuss=ext.getStatusList();
            
            ext.populatebbList();
           DisplayBillboardUnderVendorController ext1=new DisplayBillboardUnderVendorController ();
            
            List<SelectOption>ListStatus=ext1.getStatusList();
            ext1.strStatus = 'All Billboards';
            ext1.populatebbList();
           
*/             
    } 
     // End of test Method 

}