@isTest
public class TestSpecificationTemplateListViewExt {

    static testmethod void testSpecTemplistview(){
      /*Specification_Template__c testST=new Specification_Template__c(Name='SPT007');
          insert testST;
        SpecificationTemplateListViewExt spectemp=new SpecificationTemplateListViewExt(new Apexpages.StandardController (testST));
        spectemp.spetlistview();
        
*/        
    }
        
    
}