@isTest
public class TestEditSpecItemSwitchExt {
  /*  
    testmethod static void editSpecItem(){
        
          Specification_Template__c testST1=new Specification_Template__c(Name='Testing Specification Template');
         insert testST1;
            Spec_Item__c testSPI1=new Spec_Item__c(Name='Test Spec Item 1',Specification_Template__c=testST1.Id);
         insert testSPI1;
        
        EditSpecItemSwitchExt eSpecon=new EditSpecItemSwitchExt(new Apexpages.standardController (testSPI1));
        
        
    }*/
    

}