@isTest
public class TestScheduleTemplateListViewSwitchExt {
    
     static testmethod void testMethodScheTemp(){
     /*    Media_Type__c testMedia=new Media_Type__c(Name='MT012');
          insert testMedia;
          Schedule_Template__c testST=new Schedule_Template__c(Name='ST012',Media_Types__c=testMedia.Id);
          insert testST;
       ScheduleTemplateListViewSwitchExt scheTemp=new ScheduleTemplateListViewSwitchExt(new Apexpages.StandardController(testST));
         //scheTemp.theme='Theme4d';
        Apexpages.pageReference result;
        result=scheTemp.sclistview();
         system.assertEquals(false,scheTemp.isLtng);*/
    }

}