@istest
Public class TestDeleteProductionEstimateTemplateExt
{

	  static testMethod void TestDeleteProductionEstimateTemplateExt()
      {
         /* Client__c testClient=new Client__c(Name='Test client');
           insert testClient; 
          
          Client__c client=new Client__c(name='Test');
          insert client;
          
          Production_Estimate_Template__c   testIAl=new Production_Estimate_Template__c(Name='Test Name');
          insert testIAl;
          
          
          ApexPages.CurrentPage().getParameters().put('id',testIAl.id);
         
             // Instantiate the standard controller with the Client
          ApexPages.StandardController con = new ApexPages.StandardController(testIAl);
        
            // Instantiate the extention instance with the standardcontroller
          DeleteProductionEstimateTemplateExt ext = new DeleteProductionEstimateTemplateExt(con);
        
        // ext.isError = True;          
            // Invoke the Delete method on the extension
          ApexPages.PageReference result = ext.CheckDelete();
          
        
          result = ext.CheckDelete();
          */
     }// End of Test Coverage


}