//@isTest
public class TestEditTagtempLineItemsExt {
/*	static TestMethod void TestEditTagtempLineItemsExt(){
        
        Tag_Template__c testtag=new Tag_Template__c(Name='tags');
        insert testtag;
        Tag_Template_Item__c testtagLI=new Tag_Template_Item__c(name='tagli',TagTemplate__c=testtag.id);
        insert testtagLI;
        
        EditTagtempLineItemsExt controller = new EditTagtempLineItemsExt(new ApexPages.StandardController(testtagLI));
        controller.saveme();
        controller.cancelme();
	}*/
}