@isTest
public class TestEditScheduleTaskSwitchExt {

  /*  @istest static void TestEditMethod(){
        Schedule_Template__c testST1=new Schedule_Template__c(Name='Testing Schedule Template',Active__c=True);
        insert testST1;
        GL_Department__c testGLD = new GL_Department__c(Name='TestGLD996');
        insert testGLD;
         GL_Code__c testGL=new GL_Code__c(Name='GL Code 9988',GL_ID__c='TestGL9988',GL_Department__c = testGLD.id);
        insert testGL;
         Schedule_Task__c testSCT1=new Schedule_Task__c(Name='Test Schedule Task 1',Schedule_Template__c=testST1.Id,GL_Code__c = testGL.id);
        insert testSCT1;
         EditScheduleTaskSwitchExt EditSchTask=new EditScheduleTaskSwitchExt(new Apexpages.StandardController(testSCT1));
        
        
    }*/
}