//@istest
public class TestMaterialLineDetailPageExtension    {

  // Test Method 
  /*static testMethod void TestMaterialLineDetailPageExtension    ()
    {
       Material_Item__c ML = new Material_Item__c();
       ApexPages.StandardController con=new ApexPages.StandardController(ML);
       MaterialLineDetailPageExtension ext=new MaterialLineDetailPageExtension(con);
       
    } */
 // End of test Method


}