@isTest
Public class TestAdminListViewController{
/*
 static testMethod void TestAdminListViewController()
        {
             ApexPages.currentPage().getParameters().put('intFocus', '1');
             AdminListViewController ext1=new AdminListViewController();
             
             System.assertEquals('GL Codes',ext1.tabInFocus);
             
             ApexPages.currentPage().getParameters().put('intFocus', '2');
             AdminListViewController ext2=new AdminListViewController();
 
             ApexPages.currentPage().getParameters().put('intFocus', '3');
             AdminListViewController ext3=new AdminListViewController();
             
             ApexPages.currentPage().getParameters().put('intFocus','4');
             AdminListViewController ext4=new AdminListViewController();
             
             ApexPages.currentPage().getParameters().put('intFocus', '5');
             AdminListViewController ext5=new AdminListViewController();
 
             ApexPages.currentPage().getParameters().put('intFocus', '6');
             AdminListViewController ext6=new AdminListViewController();
             
             ApexPages.currentPage().getParameters().put('intFocus','11');
             AdminListViewController ext11=new AdminListViewController(); 
             
             ApexPages.currentPage().getParameters().put('intFocus','8');
             AdminListViewController ext8=new AdminListViewController();
             
             ApexPages.currentPage().getParameters().put('intFocus','9');
             AdminListViewController ext9=new AdminListViewController();
             
             ApexPages.currentPage().getParameters().put('intFocus','10');
             AdminListViewController ext10=new AdminListViewController();
             
             ApexPages.currentPage().getParameters().put('intFocus','12');
             AdminListViewController ext12=new AdminListViewController();
        }

*/
}