@isTest
public class TestProductionSpecTemplateListviewSwtich {
    
    testmethod static void prospecListView(){
   /*  Production_Spec_Template__c testPST=new Production_Spec_Template__c(Name='Testing Production Spec Template 0001');
        insert testpst;
        ProductionSpecTemplateListviewSwitcheXT  pspec=new ProductionSpecTemplateListviewSwitcheXT(new ApexPages.StandardController(testPST));
        pspec.PsTemplistview();
       */
    }
    

}