@isTest
public class TestQuoteSpecViewSwitchExt {
	static TestMethod void TestQuoteSpecViewSwitchExt  (){
      /*  job__c job=new job__c(Name='testjob');
        insert job;
        Quote__c testQ=new Quote__c(name='quote',job__c=job.id);
        insert testQ;
        Quote_Spec_Item__c testQSpec=new Quote_Spec_Item__c(Name='Camp',Quote__c=testQ.id);
        insert testQSpec;
        QuoteSpecViewSwitchExt controller = new QuoteSpecViewSwitchExt (new ApexPages.StandardController(testQSpec));
       // boolean x = controller.isMobile;
       controller.pagedir();*/
    }
}