@istest
public class TestDisplayPEstimateSpecItemsController {
    @istest static void TestDisplayPEstimateSpecItemsController(){
       /* 
          Production_Estimate_Template__c   testIAl=new Production_Estimate_Template__c  (Name='Test Name');
          insert testIAl;
        
        Production_Estimate_Temp_Line_Items__c testPELt=new Production_Estimate_Temp_Line_Items__c(Name='LineItem Test',Production_Estimate_Template__c=testIAl.id);
         
            ApexPages.CurrentPage().getParameters().put('id',testIAl.id);
            DisplayPEstimateSpecItemsController ext=new DisplayPEstimateSpecItemsController();
          ext.createSpecitems();
          ext.save();
          ext.cancelme();*/
           
    }
    
}