@isTest
public class TestInvoiceSwitchExt {
	 static TestMethod void TestInvoiceSwitchExt(){
      /*  Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        Invoice__c testInv=new Invoice__c(Name='Camp',Job__c=testJob1.id);
        insert testInv;
        InvoiceSwitchExt controller = new InvoiceSwitchExt(new ApexPages.StandardController(testInv));
      //  boolean x = controller.isMobile;*/
}
}