@isTest
public class TestCreateProductionEstimateTemplateExt {
    
    static testMethod void TestCreateProductionEstimateTemplateExt (){
/*
          Production_Estimate_Template__c TestIAT=new Production_Estimate_Template__c(Name='Test IAT');
          ApexPages.StandardController con=new ApexPages.StandardController(TestIAT);
     
           // Instantiate the extention instance with the standard controller
           CreateProductionEstimateTemplateExt ext =new CreateProductionEstimateTemplateExt(con);
        
           // Invoke the primary method on the extension 
           ApexPages.PageReference result1=ext.saveme();
           ApexPages.PageReference result2=ext.cancelme();
      */
}

}