//@isTest
public class TestMIViewNote {
  /*  static testMethod void TestMIViewNote()
    {
          Material_Item__c  testI=new Material_Item__c (name='test 123',Calc_Unit__c ='Size');
  		  insert testI;
               
          System.assertEquals('test 123',testI.Name);  
          
          Note n=new Note(parentId=testI.Id,Title='Test Title 852',IsPrivate=True,Body='Test Note Body');
               insert n;
              
          ApexPages.StandardController con=new ApexPages.StandardController(testI);
                   
          ApexPages.currentPage().getParameters().put('Id', n.Id);
               
          MIViewNote ext= new MIViewNote(con);
          ApexPages.Pagereference result1=ext.Cancel();
          result1=ext.editNote();
          result1=ext.deleteNote();
     }
    
    static testMethod void TestEditMINoteLightningExt()
    {
          Material_Item__c  testI1=new Material_Item__c (name='test 12341',Calc_Unit__c ='Size');
  		  insert testI1;
               
          System.assertEquals('test 12341',testI1.Name);  
          
          Note n1=new Note(parentId=testI1.Id,Title='Test Title 8521',IsPrivate=True,Body='Test Note Body');
               insert n1;
              
          ApexPages.StandardController con1=new ApexPages.StandardController(n1);
                   
          System.currentPagereference().getParameters().put('Id', n1.Id);
               
          EditMINoteLightningExt ext1= new EditMINoteLightningExt(con1);
          ApexPages.Pagereference result1=ext1.cancelme();
          result1=ext1.SaveNote();
          //result1=ext1.cancelme();
          
          DeleteMINoteExtension ext3=new DeleteMINoteExtension(con1);
          Apexpages.pagereference res=ext3.checkDelete();
        
     }*/
}