//@isTest
Public class TestCreateMaterialInventoryExtension{
/*static testMethod void TestCreateMaterialInventoryExtension(){

    Material_Item__c  testI=new Material_Item__c (name='test 123');
    insert testI;
   
    Material_Inventory_Item__c mi= new Material_Inventory_Item__c(Material_Item__c=testI.id);
    
    
    ApexPages.currentPage().getParameters().put('materialid',testI.Id);
    ApexPages.StandardController con=new ApexPages.StandardController(mi);
     
           // Instantiate the extention instance with the standard controller
           CreateMaterialInventoryExtension ext =new CreateMaterialInventoryExtension(con);
    ApexPages.PageReference result1=ext.saveme();
    ApexPages.PageReference result2=ext.cancelme();
    

}*/

}