//@isTest
Public class TestDisplayMaterialInventoryController{

/*Static testMethod void TestDisplayMaterialInventoryController()
     {
            Material_Item__c  testI=new Material_Item__c (name='test 123',Qty_On_Hand__c=0, Case_Pack__c=10.00);
            insert testI;
   
            Material_Inventory_Item__c mi= new Material_Inventory_Item__c(Material_Item__c=testI.id,Qty_On_Shelf__c=10.00);
            insert mi;
                    
            ApexPages.currentPage().getParameters().put('id',testI.Id);
         // Instantiate the extention instance with the Custom Controller
           DisplayMaterialInventoryController ext1=new DisplayMaterialInventoryController();
          
            // Invoke the primary method on the extension
           ApexPages.PageReference result1=ext1.createMI();
           
           ext1.strMI = mi.Id;
           result1 = ext1.deleteMI();
      } 
     // End of test Method
*/



}