//@isTest
public class TestEditTagtempLineItemsSwitchExt {
	/*static TestMethod void TestEditTagtempLineItemsSwitchExt(){
        
        Tag_Template__c testtag=new Tag_Template__c(Name='tags');
        insert testtag;
        Tag_Template_Item__c testtagLI=new Tag_Template_Item__c(name='tagli',TagTemplate__c=testtag.id);
        insert testtagLI;
        
        EditTagtempLineItemsSwitchExt controller = new EditTagtempLineItemsSwitchExt(new ApexPages.StandardController(testtagLI));
	}*/
}