@isTest
public class TestInvoiceViewSwitchExt {
	static TestMethod void TestInvoiceViewSwitchExt(){
     /*   job__c job=new job__c(Name='testjob');
        insert job;
        Invoice__c Inv=new Invoice__c(Name='Inv',job__c=job.id);
        insert Inv;
       
        InvoiceViewSwitchExt controller = new InvoiceViewSwitchExt(new ApexPages.StandardController(Inv));
       // boolean x = controller.isMobile;
       controller.pagedir();*/
    }

}