//@isTest
public class TestDevItemsTabExt {
	/* static TestMethod void TestDevItemsTabExt(){
        List<Development_Item__c> lstDevs=new List<Development_Item__c>();
		Development_Item__c testDev=new Development_Item__c(Name='Dev');
        insert testDev;
        lstDevs.add(testDev);
        Development_Item__c testDev1=new Development_Item__c(Name='Dev1');
        insert testDev1;
        lstDevs.add(testDev1);
        DevItemsTabExt controller = new DevItemsTabExt(new ApexPages.StandardSetController(lstDevs));
       controller.isLtng=true;
        Apexpages.pagereference p=controller.Devlistview();
	}*/
}