@isTest
public class TestEstimateViewSwitchExt {
	static TestMethod void TestEstimateViewSwitchExt(){
     /*   job__c job=new job__c(Name='testjob');
        insert job;
        Estimate_Line_Items__c Est=new Estimate_Line_Items__c(Name='Est',job__c=job.id);
        insert Est;
       
        EstimateViewSwitchExt controller = new EstimateViewSwitchExt(new ApexPages.StandardController(Est));
       // boolean x = controller.isMobile;
       controller.pagedir();*/
    }
}