@isTest
Public Class TestVendorListViewExt {

 static testmethod void TestVendorListViewExt (){
 /*
   Vendor__c c=new Vendor__c(name='test');
   insert c;
   
    Billboard__c  testI=new Billboard__c(BB_Vendor__c=c.Id,name='test 123');
    insert testI;
   
    ApexPages.StandardController con = new ApexPages.StandardController(c);
     VendorListViewExt ext=new VendorListViewExt(con);
           
       */    
 
 }

}