@istest
Public class TestEditBillboardInvoicePaymentext {

static testMethod void TestEditBillboardInvoicePaymentext()
      {
       /*    Client__c testClient=new Client__c(Name='Test client');
           insert testClient; 
           Vendor__c testvendor=new Vendor__c (Name='Test vendor',Vendor_Type__c ='Outdoor');
           insert testvendor; 
   
           Billboard__c  testI=new Billboard__c(Client_Name__c=testClient.Id,name='test 123',BB_Vendor__c=testvendor.id);
           insert testI;
          System.assertEquals('test 123',testI.Name);
          
          Billboard_Invoice__c bbi=new Billboard_Invoice__c(Billboard__c=testI.id);
          insert bbi;
          BB_Invoice_Payment__c   bbili=new BB_Invoice_Payment__c  (Billboard_Invoice__c=bbi.id);
          insert bbili;
          
          
         BB_Invoice_Payment__c  testBBili = [Select id,name from BB_Invoice_Payment__c where id =:bbili.Id];
         
          // Instantiate the standard controller with the Client
          ApexPages.StandardController con = new ApexPages.StandardController(testBBili);
          EditBillboardInvoicePaymentext  ext = new EditBillboardInvoicePaymentext(con);
          ApexPages.PageReference result1=ext.saveme();
           ApexPages.PageReference result2=ext.cancelme();
           
          
*/          
  }
  }