@istest
public class TestSpecTemplateDetailSwitchExt {

    static testmethod void testspectemplateDetails(){
     /*   
            Specification_Template__c testST1=new Specification_Template__c(Name='Testing Specification Template');
         insert testST1;
            Spec_Item__c testSPI1=new Spec_Item__c(Name='Test Spec Item 1',Specification_Template__c=testST1.Id);
         insert testSPI1;
        SpecTemplateDetailSwitchExt specDcont=new SpecTemplateDetailSwitchExt(new Apexpages.standardController(testSPI1));
        Apexpages.pagereference resulst=specDcont.spedatailview();
        */
    } 
}