@isTest
public class TestScheduleTemplateDetailSwitchExt {
	static testmethod void TestScheduleTemplateDetailSwitchExt(){
        /* Media_Type__c testMedia=new Media_Type__c(Name='MT012');
          insert testMedia;
          Schedule_Template__c testST=new Schedule_Template__c(Name='ST012',Media_Types__c=testMedia.Id);
          insert testST;
        Schedule_Task__c testSTask=new Schedule_Task__c(Name='ST012',Schedule_Template__c=testST.Id);
          insert testSTask;
       ScheduleTemplateDetailSwitchExt scheTemp=new ScheduleTemplateDetailSwitchExt(new Apexpages.StandardController(testSTask));
         //scheTemp.theme='Theme4d';
         scheTemp.stlistview();
        Apexpages.pageReference result;
        //result=scheTemp.stlistview();
         system.assertEquals(false,scheTemp.isLtng);*/
    }
}