@isTest
public class TestProSpecTemplateDetailSwitchExt {

    static testmethod void testspecTemplateDeatils(){
        
/*      Production_Spec_Template__c testPST=new Production_Spec_Template__c(Name='PST0001');
       insert testPST;
     Production_Spec_Item__c testPSI=new Production_Spec_Item__c(Name='TestPSI0001',Production_Spec_Template__c=testPST.Id);
        insert testPSI;
             
             ProSpecTemplateDetailSwitchExt prospecDetail=new ProSpecTemplateDetailSwitchExt(new ApexPages.StandardController(testPSI));
             prospecDetail.pstDetailview();
            */
         
    }
}