@isTest
public class Test_DetailJobSwitchPageExt  {
   /* static TestMethod void Test_DetailJobSwitchPageExt  (){
        Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        DetailJobSwitchPageExt controller = new DetailJobSwitchPageExt (new ApexPages.StandardController(testJob1));
        boolean x = controller.isMobile;        
       ApexPages.Pagereference ct= controller.jobMobileRedirection();
        controller.th='Theme4d';
        ct= controller.jobMobileRedirection();
        controller.th='Theme4t';
        ct= controller.jobMobileRedirection();
        
    }
   
    static TestMethod void Test_DetailJobSwitchPageExt2  (){
        Job__c testJob1=new Job__c(Name='Job858',Start_Date__c=System.Today());
        insert testJob1;
        JobSwitchExt controller = new JobSwitchExt (new ApexPages.StandardController(testJob1));
       // boolean x = controller.isMobile;
       
    }*/
    
}