//@istest
Public class TestDisplayBillboardInvoiceLIController{

/*static testMethod void TestDisplayBillboardInvoiceLIController()
      {
           Client__c testClient=new Client__c(Name='Test client');
           insert testClient; 
           Vendor__c testvendor=new Vendor__c (Name='Test vendor',Vendor_Type__c ='Outdoor');
           insert testvendor; 
   
           Billboard__c  testI=new Billboard__c(Client_Name__c=testClient.Id,name='test 123',BB_Vendor__c=testvendor.id);
           insert testI;
          System.assertEquals('test 123',testI.Name);
          
          Billboard_Invoice__c bbi=new Billboard_Invoice__c(Billboard__c=testI.id);
            insert bbi;
          Billboard_Invoice_Line_Item__c bbili=new Billboard_Invoice_Line_Item__c(Billboard_Invoice__c=bbi.id);
          insert bbili;
         
          ApexPages.currentPage().getParameters().put('id',bbi.Id);
    // Instantiate the extention instance with the Custom Controller
           DisplayBillboardInvoiceLIController  ext1=new DisplayBillboardInvoiceLIController();
           
            // Invoke the primary method on the extension
           ApexPages.PageReference result1=ext1.createIALI();
           result1 = ext1.createIALI();
           ext1.strBBILI= bbili.Id;
           result1 = ext1.save();
           result1 = ext1.cancelme();
           result1 = ext1.deleteIALI();
           result1 = ext1.EditBBIL();
           
           
           
           
 }*/
 }