//@isTest
Public class TestCreateNewMaterialExtension {
/*static testMethod void TestCreateNewMaterialExtension (){

           Recordtype rt=[SELECT ID, name FROM RecordType WHERE Name ='Each'];
   
           Material_Item__c  testI=new Material_Item__c (name='test 123');

           ApexPages.currentPage().getParameters().put('RecordType',rt.Id);
           ApexPages.StandardController con=new ApexPages.StandardController(testI);
     
           // Instantiate the extention instance with the standard controller
           CreateNewMaterialExtension ext =new CreateNewMaterialExtension(con);
        
           // Invoke the primary method on the extension 
           ApexPages.PageReference result1=ext.saveme();
           ApexPages.PageReference result2=ext.cancelme();
           List<SelectOption> Departments=ext.getGLDepartments();
           List<SelectOption> Codes=ext.getGLCodes() ;
           string result4=ext.getGLDName();
           string result5=ext.getGLCName();
           
           ext.setGLCName ('Test GLC');
           ext.setGLDName('Test GLD');
           ext.getCBTempName();
    	   ext.getPETempName();
    	   ext.getCBTemp();
    	   ext.getPETemp();
    ext.setCBTemp('test');
    ext.setPETemp('test');
       

}*/
}