@istest
public class TestEditProductionEstimateTemplateExt {
    
    static testMethod void TestEditProductionEstimateTemplateExt()
      {/*
           Production_Estimate_Template__c   testIAl=new Production_Estimate_Template__c  (Name='Test Name');
          insert testIAl;
         
          
           Production_Estimate_Template__c    testBB = [Select id,name from Production_Estimate_Template__c    where id =:testIAl.Id];
         
             // Instantiate the standard controller with the Client
          ApexPages.StandardController con = new ApexPages.StandardController(testBB);
           ApexPages.CurrentPage().getParameters().put('id',testBB.id);
            // Instantiate the extention instance with the standardcontroller
          
          EditProductionEstimateTemplateExt ext = new EditProductionEstimateTemplateExt(con);
        
        // Invoke the primary method on the extension */
         /* ApexPages.PageReference result1=ext.saveme();
          ApexPages.PageReference result2=ext.cancelme();
          
        */
          
     }// End of Test Coverage


}